project:
  type: book
  output-dir: docs/

engine: knitr

book:
  title: "XX_NAME_XX"
  author: "XX_AUTHOR_XX"
  date: "XX_DATE_XX"
  chapters:
    - index.qmd
    - code/qmd/references.qmd
    - code/qmd/session_info.qmd
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/
  favicon: img/dummy.svg
bibliography: code/qmd/references.bib

from: markdown+emoji

format:
  html:
    theme:
    - simplex
    - code/css/styles.scss
    code-fold: true
    code-summary: "toggle code"
    mainfont: "'TeX Gyre Pagella', 'Crimson Text', 'Noto Serif', serif"
    monofont: "'Fira Code', 'Ubuntu mono', monospace"
    fig-format: "svg"

execute:
  message: false
  warning: false

crossref:
  fig-title: Figure     # (default is "Figure")
  fig-prefix: Fig   # (default is "fig.")
  tbl-title: Table     # (default is "Table")
  tbl-prefix: Tab    # (default is "tbl.")
  eq-title: Equation     # (default is "Table")
  eq-prefix: eq    # (default is "tbl.")

highlight-style: printing # zenburn